### ISSUE TITLE
Provider id should be a characters only

### ISSUE THREAD

**Issue by nyalldawson** [Dan-Eli/geobato#22]
https://github.com/Dan-Eli/GeoSim/blob/f8cdc16693c500a247f146831d5b8cc8ea4b9038/geo_sim_processing_provider.py#L72

Instead of 'Geo Simplification', this should be 'geosimplification'. The id isn't shown anywhere, and should contain alphanumeric characters only.

**Comment by Dan-Eli** [comment]
@nyalldawson issue corrected
