### ISSUE TITLE
chordalaxis display name should be translated

### ISSUE THREAD

**Issue by nyalldawson** [Dan-Eli/geobato#23]
https://github.com/Dan-Eli/GeoSim/blob/f8cdc16693c500a247f146831d5b8cc8ea4b9038/chordal_axis_algorithm.py#L75

should return

    return self.tr('Chordal Axis')

(also a very minor HIG note -- algorithm names should ideally be sentence case for consistency, i.e. "Chordal axis")

**Comment by Dan-Eli** [comment]
@nyalldawson issue corrected in choral_axis_algorithm.py, reduce_bend_algorithm.py and simplify_algorithm.py
